server.port=9090
spring.application.name=demo

spring.ai.vectorstore.chroma.initialize-schema=true

spring.ai.vectorstore.chroma.collection-name=modules
spring.ai.vectorstore.chroma.database=default
spring.ai.vectorstore.chroma.tenant=default
spring.ai.vectorstore.chroma.port=8000


# 1. Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/assign

# 2. DB Credentials
spring.datasource.username=demo_user
spring.datasource.password=password

# 3. Driver class (optional, auto-detected)
spring.datasource.driver-class-name=org.postgresql.Driver

# Show SQL in console
spring.jpa.show-sql=true

# Tell Hibernate it's PostgreSQLd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
